opensixtSxTranslateBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: opensixtSxTranslateBundle:Default:index }

_sxtranslate_getfromts:
    pattern: /sxtranslate/getfromts/
    defaults: { _controller: opensixt.sx_translate.controller.import:getFromTsAction}

_sxfreetext_add:
    pattern: /freetext/add/
    defaults: { _controller: opensixt.sx_translate.controller.freetext:addAction}

_sxfreetext_edit:
    pattern: /freetext/edit/{locale}/{page}
    defaults: { _controller: opensixt.sx_translate.controller.freetext:editAction, locale: 'empty', page: 1 }

_sxfreetext_status:
    pattern: /freetext/status/{page}
    defaults: { _controller: opensixt.sx_translate.controller.freetext:statusAction, page: 1 }

