parameters:
    opensixt.sx_translate.controller.import.class: opensixt\SxTranslateBundle\Controller\ImportController

services:
    opensixt.sx_translate.controller.import:
        class: %opensixt.sx_translate.controller.import.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            importer: @opensixt.bikini_translate.sevices.exporter
