parameters:
    opensixt.sx_translate.controller.import.class: opensixt\SxTranslateBundle\Controller\ImportController
    opensixt.sx_translate.controller.addfreetext.class: opensixt\SxTranslateBundle\Controller\AddFreeTextController
    opensixt.sx_translate.controller.editfreetext.class: opensixt\SxTranslateBundle\Controller\EditFreeTextController

    opensixt.sx_translate.intermediate.handlefreetext.class: opensixt\SxTranslateBundle\IntermediateLayer\HandleFreeText
    opensixt.sx_translate.controller.editfreetext.pagination_limit: "15"

services:
    opensixt.sx_translate.controller.import:
        class: %opensixt.sx_translate.controller.import.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            importer: @opensixt.bikini_translate.sevices.exporter

    opensixt.sx_translate.controller.addfreetext:
        class: %opensixt.sx_translate.controller.addfreetext.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            handleFreeText: @opensixt.sx_translate.intermediate.handlefreetext
            doctrine: @doctrine
            commonLanguage: %common_language%

    opensixt.sx_translate.controller.editfreetext:
        class: %opensixt.sx_translate.controller.editfreetext.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            handleFreeText: @opensixt.sx_translate.intermediate.handlefreetext
            doctrine: @doctrine
            commonLanguage: %common_language%


    opensixt.sx_translate.intermediate.handlefreetext:
        class: %opensixt.sx_translate.intermediate.handlefreetext.class%
        arguments: [@doctrine]
        properties:
            securityContext: @security.context
            paginator: @knp_paginator
            paginationLimit: %opensixt.sx_translate.controller.editfreetext.pagination_limit%
            revisionControlMode: %text_revision_control%
