parameters:
#    opensixt_sx_translate.example.class: opensixt\SxTranslateBundle\Example

services:
#    opensixt_sx_translate.example:
#        class: %opensixt_sx_translate.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
