_home:
    pattern: /
    defaults: { _controller: OpensixtBikiniTranslateBundle:Default:index, page: 'index' }

_login:
    pattern:  /login
    defaults: { _controller: OpensixtBikiniTranslateBundle:Security:login }

_login_check:
    pattern: /login_check

_logout:
    pattern: /logout

_translate_home:
    pattern: /translate/
    defaults: { _controller: OpensixtBikiniTranslateBundle:Translate:index }

_translate_setlocale:
    pattern: /translate/setlocale/
    defaults: { _controller: opensixt.bikini_translate.controller.setlocale:setlocaleAction }

_translate_edittext:
    pattern: /translate/edittext/{locale}/{page}
    defaults: { _controller: opensixt.bikini_translate.controller.edittext:edittextAction, locale: 'empty', page: 1 }
    requirements:
        page: \d+

_translate_searchstring:
    pattern: /translate/searchstring/{page}
    defaults: { _controller: opensixt.bikini_translate.controller.searchstring:searchstringAction, page: 1 }
    requirements:
        page: \d+

_translate_changetext:
    pattern: /translate/changetext/{page}
    defaults: { _controller: opensixt.bikini_translate.controller.changetext:changetextAction, page: 1 }
    requirements:
        page: \d+

_translate_cleantext:
    pattern: /translate/cleantext/{page}
    defaults: { _controller: opensixt.bikini_translate.controller.cleantext:cleantextAction, page: 1 }
    requirements:
        page: \d+

_translate_copylanguage:
    pattern: /translate/copylanguage/
    defaults: { _controller: opensixt.bikini_translate.controller.copylanguage:copylanguageAction }

_translate_copyresource:
    pattern: /translate/copyresource/
    defaults: { _controller: opensixt.bikini_translate.controller.copyresource:copyresourceAction }

_translate_releasetext:
    pattern: /translate/releasetext/{page}
    defaults: { _controller: opensixt.bikini_translate.controller.releasetext:releasetextAction, page: 1 }
    requirements:
        page: \d+

_translate_sendtots:
    pattern: /translate/sendtots/{locale}
    defaults: { _controller: opensixt.bikini_translate.controller.sendtotranslationservice:sendtotsAction, locale: 'empty' }

_translate_ajax_savetext:
    pattern: /translate/savetext/
    defaults: { _controller: opensixt.bikini_translate.controller.ajaxresponder:savetextAction}
