parameters:
    opensixt.bikini_translate.controller.abstract.class: Opensixt\BikiniTranslateBundle\Controller\AbstractController
    opensixt.bikini_translate.controller.edittext.class: Opensixt\BikiniTranslateBundle\Controller\EditTextController
    opensixt.bikini_translate.controller.setlocale.class: Opensixt\BikiniTranslateBundle\Controller\SetLocaleController
    opensixt.bikini_translate.controller.searchstring.class: Opensixt\BikiniTranslateBundle\Controller\SearchStringController
    opensixt.bikini_translate.controller.changetext.class: Opensixt\BikiniTranslateBundle\Controller\ChangeTextController
    opensixt.bikini_translate.controller.cleantext.class: Opensixt\BikiniTranslateBundle\Controller\CleanTextController
    opensixt.bikini_translate.controller.releasetext.class: Opensixt\BikiniTranslateBundle\Controller\ReleaseTextController
    opensixt.bikini_translate.controller.sendtotranslationservice.class: Opensixt\BikiniTranslateBundle\Controller\SendToTranslationServiceController
    opensixt.bikini_translate.controller.copylanguage.class: Opensixt\BikiniTranslateBundle\Controller\CopyLanguageController
    opensixt.bikini_translate.controller.copyresource.class: Opensixt\BikiniTranslateBundle\Controller\CopyResourceController
    opensixt.bikini_translate.controller.ajaxresponder.class: Opensixt\BikiniTranslateBundle\Controller\AjaxResponderController

    opensixt.bikini_translate.intermediate.searchstring.class: Opensixt\BikiniTranslateBundle\IntermediateLayer\SearchString
    opensixt.bikini_translate.intermediate.searchstring.pagination_limit: "15"

    opensixt.bikini_translate.intermediate.edittext.class: Opensixt\BikiniTranslateBundle\IntermediateLayer\EditText
    opensixt.bikini_translate.intermediate.edittext.pagination_limit: "15"

    opensixt.bikini_translate.intermediate.flaggedtext.class: Opensixt\BikiniTranslateBundle\IntermediateLayer\FlaggedText
    opensixt.bikini_translate.intermediate.flaggedtext.pagination_limit: "15"

    opensixt.bikini_translate.intermediate.copydomain.class: Opensixt\BikiniTranslateBundle\IntermediateLayer\CopyDomain

    opensixt.bikini_translate.sevices.exporter.class: Opensixt\BikiniTranslateBundle\Helpers\BikiniExport
    opensixt.bikini_translate.sevices.flash.class: Opensixt\BikiniTranslateBundle\Helpers\BikiniFlash

    opensixt.bikini_translate.acl_helper.abstract.class: Opensixt\BikiniTranslateBundle\AclHelper\AbstractHelper
    opensixt.bikini_translate.acl_helper.user.class: Opensixt\BikiniTranslateBundle\AclHelper\User
    opensixt.bikini_translate.acl_helper.language.class: Opensixt\BikiniTranslateBundle\AclHelper\Language
    opensixt.bikini_translate.acl_helper.group.class: Opensixt\BikiniTranslateBundle\AclHelper\Group
    opensixt.bikini_translate.acl_helper.resource.class: Opensixt\BikiniTranslateBundle\AclHelper\Resource

    opensixt.bikini_translate.listener.doctrine.flush.class: Opensixt\BikiniTranslateBundle\EventListener\Doctrine\Flush
    opensixt.bikini_translate.listener.kernel.controller.class: Opensixt\BikiniTranslateBundle\EventListener\Kernel\Controller

services:
    opensixt.bikini_translate.controller.abstract:
        class: %opensixt.bikini_translate.controller.abstract.class%
        abstract: true
        properties:
            request: @request
            session: @session
            translator: @translator
            em: @doctrine.orm.entity_manager
            formFactory: @form.factory
            templating: @templating
            securityContext: @security.context
            aclProvider: @security.acl.provider
            router: @router
            toolLanguage: %tool_language%
            bikiniFlash: @opensixt.bikini_translate.sevices.flash
            breadcrumbs: @white_october_breadcrumbs

    opensixt.bikini_translate.controller.edittext:
        class: %opensixt.bikini_translate.controller.edittext.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            editText: @opensixt.bikini_translate.intermediate.edittext

    opensixt.bikini_translate.controller.setlocale:
        class: %opensixt.bikini_translate.controller.setlocale.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request

    opensixt.bikini_translate.controller.searchstring:
        class: %opensixt.bikini_translate.controller.searchstring.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            searcher: @opensixt.bikini_translate.intermediate.searchstring

    opensixt.bikini_translate.controller.changetext:
        class: %opensixt.bikini_translate.controller.changetext.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            searcher: @opensixt.bikini_translate.intermediate.searchstring

    opensixt.bikini_translate.controller.cleantext:
        class: %opensixt.bikini_translate.controller.cleantext.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            searcher: @opensixt.bikini_translate.intermediate.flaggedtext

    opensixt.bikini_translate.controller.releasetext:
        class: %opensixt.bikini_translate.controller.releasetext.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            searcher: @opensixt.bikini_translate.intermediate.flaggedtext

    opensixt.bikini_translate.controller.sendtotranslationservice:
        class: %opensixt.bikini_translate.controller.sendtotranslationservice.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            searcher: @opensixt.bikini_translate.intermediate.edittext
            exporter: @opensixt.bikini_translate.sevices.exporter

    opensixt.bikini_translate.controller.copylanguage:
        class: %opensixt.bikini_translate.controller.copylanguage.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            searcher: @opensixt.bikini_translate.intermediate.copydomain

    opensixt.bikini_translate.controller.copyresource:
        class: %opensixt.bikini_translate.controller.copyresource.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            searcher: @opensixt.bikini_translate.intermediate.copydomain

    opensixt.bikini_translate.controller.ajaxresponder:
        class: %opensixt.bikini_translate.controller.ajaxresponder.class%
        parent: opensixt.bikini_translate.controller.abstract
        scope: request
        properties:
            searcher: @opensixt.bikini_translate.intermediate.searchstring


    opensixt.bikini_translate.intermediate.edittext:
        class: %opensixt.bikini_translate.intermediate.edittext.class%
        arguments: [@doctrine]
        properties:
            paginator: @knp_paginator
            securityContext: @security.context
            commonLanguage: %common_language%
            exportChunkLimit: %export_chunk_limit%
            paginationLimit: %opensixt.bikini_translate.intermediate.edittext.pagination_limit%

    opensixt.bikini_translate.intermediate.searchstring:
        class: %opensixt.bikini_translate.intermediate.searchstring.class%
        arguments: [@doctrine]
        properties:
            paginator: @knp_paginator
            securityContext: @security.context
            paginationLimit: %opensixt.bikini_translate.intermediate.searchstring.pagination_limit%

    opensixt.bikini_translate.intermediate.flaggedtext:
        class: %opensixt.bikini_translate.intermediate.flaggedtext.class%
        arguments: [@doctrine]
        properties:
            paginator: @knp_paginator
            securityContext: @security.context
            paginationLimit: %opensixt.bikini_translate.intermediate.flaggedtext.pagination_limit%

    opensixt.bikini_translate.intermediate.copydomain:
        class: %opensixt.bikini_translate.intermediate.copydomain.class%
        arguments: [@doctrine, %common_language%]

    opensixt.bikini_translate.sevices.exporter:
        class: %opensixt.bikini_translate.sevices.exporter.class%
        properties:
            sourceLanguage: %tool_language%

    opensixt.bikini_translate.sevices.flash:
        class: %opensixt.bikini_translate.sevices.flash.class%
        properties:
            session: @session
            translator: @translator

    opensixt.bikini_translate.menu_builder:
        class: Opensixt\BikiniTranslateBundle\Menu\MenuBuilder
        properties:
          factory: @knp_menu.factory
          translator: @translator
          eventDispatcher: @event_dispatcher
          securityContext: @security.context

    opensixt.bikini_translate.sidebar_menu:
        class: Knp\Menu\MenuItem
        factory_service: opensixt.bikini_translate.menu_builder
        factory_method: createSidebarMenu
        arguments: [@request]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: bikini_translate.sidebar_menu }

    opensixt.bikini_translate.acl_helper.abstract:
        class: %opensixt.bikini_translate.acl_helper.abstract.class%
        abstract: true
        properties:
          aclProvider: @security.acl.provider

    opensixt.bikini_translate.acl_helper.user:
        class: %opensixt.bikini_translate.acl_helper.user.class%
        parent: opensixt.bikini_translate.acl_helper.abstract

    opensixt.bikini_translate.acl_helper.language:
        class: %opensixt.bikini_translate.acl_helper.language.class%
        parent: opensixt.bikini_translate.acl_helper.abstract

    opensixt.bikini_translate.acl_helper.resource:
        class: %opensixt.bikini_translate.acl_helper.resource.class%
        parent: opensixt.bikini_translate.acl_helper.abstract

    opensixt.bikini_translate.acl_helper.group:
        class: %opensixt.bikini_translate.acl_helper.group.class%
        parent: opensixt.bikini_translate.acl_helper.abstract

    opensixt.bikini_translate.listener.doctrine.flush:
        class: %opensixt.bikini_translate.listener.doctrine.flush.class%
        tags:
          - { name: doctrine.event_listener, event: postFlush }
          - { name: doctrine.event_listener, event: onFlush }


    opensixt.bikini_translate.listener.kernel.controller:
        class: %opensixt.bikini_translate.listener.kernel.controller.class%
        properties:
          securityContext: @security.context
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onController }
