jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Opensixt\BikiniTranslateBundle\Entity\User:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_USER:        ROLE_GUEST
        ROLE_ADMIN:       [ROLE_GUEST, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: OpensixtBikiniTranslateBundle:User, property: username }

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /admin/
                always_use_default_target_path: true
                use_referer: true
            logout:
                target: /admin
            security: true
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: /admin/.*, roles: ROLE_USER }
        - { path: /translate/.*, roles: ROLE_USER }
        - { path: /freetext/.*, roles: ROLE_USER }
        - { path: /mobile/.*, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    acl:
         connection: default