_user_admin_home:
    pattern: /admin/
    defaults: { _controller: OpensixtUserAdminBundle:Default:index }

_admin_userlist:
    pattern: /admin/user/list/{page}
    defaults: { _controller: opensixt.user_admin.controller.user:listAction, page: 1 }
    requirements:
        page: \d+
        _method: get

_admin_user_create:
    pattern: /admin/user/create
    defaults: { _controller: opensixt.user_admin.controller.user:createAction }
    requirements:
        id: \d+
        _method: get

_admin_user_save_new:
    pattern: /admin/user/save
    defaults: { _controller: opensixt.user_admin.controller.user:saveNewAction }
    requirements:
        id: \d+
        _method: post

_admin_user:
    pattern: /admin/user/{id}
    defaults: { _controller: opensixt.user_admin.controller.user:viewAction }
    requirements:
        id: \d+
        _method: get

_admin_user_save:
    pattern: /admin/user/{id}/save
    defaults: { _controller: opensixt.user_admin.controller.user:saveAction }
    requirements:
        id: \d+
        _method: post

_admin_grouplist:
    pattern: /admin/group/list/{page}
    defaults: { _controller: opensixt.user_admin.controller.group:listAction, page: 1 }
    requirements:
      page: \d+
      _method: get

_admin_group_create:
    pattern: /admin/group/create
    defaults: { _controller: opensixt.user_admin.controller.group:createAction }
    requirements:
        id: \d+
        _method: get

_admin_group_save_new:
    pattern: /admin/group/save
    defaults: { _controller: opensixt.user_admin.controller.group:saveNewAction }
    requirements:
        id: \d+
        _method: post

_admin_group:
    pattern: /admin/group/{id}
    defaults: { _controller: opensixt.user_admin.controller.group:viewAction }
    requirements:
        id: \d+
        _method: get

_admin_group_save:
    pattern: /admin/group/{id}/save
    defaults: { _controller: opensixt.user_admin.controller.group:saveAction }
    requirements:
        id: \d+
        _method: post

_admin_langlist:
    pattern: /admin/language/list/{page}
    defaults: { _controller: opensixt.user_admin.controller.language:listAction, page: 1 }
    requirements:
      page: \d+
      _method: get

_admin_language_create:
    pattern: /admin/language/create
    defaults: { _controller: opensixt.user_admin.controller.language:createAction }
    requirements:
        id: \d+
        _method: get

_admin_language_save_new:
    pattern: /admin/language/save
    defaults: { _controller: opensixt.user_admin.controller.language:saveNewAction }
    requirements:
        id: \d+
        _method: post

_admin_language:
    pattern: /admin/language/{id}
    defaults: { _controller: opensixt.user_admin.controller.language:viewAction }
    requirements:
        id: \d+
        _method: get

_admin_language_save:
    pattern: /admin/language/{id}/save
    defaults: { _controller: opensixt.user_admin.controller.language:saveAction }
    requirements:
        id: \d+
        _method: post

_admin_reslist:
    pattern: /admin/resource/list/{page}
    defaults: { _controller: opensixt.user_admin.controller.resource:listAction, page: 1 }
    requirements:
      page: \d+
      _method: get

_admin_resource_create:
    pattern: /admin/resource/create
    defaults: { _controller: opensixt.user_admin.controller.resource:createAction }
    requirements:
        id: \d+
        _method: get

_admin_resource_save_new:
    pattern: /admin/resource/save
    defaults: { _controller: opensixt.user_admin.controller.resource:saveNewAction }
    requirements:
        id: \d+
        _method: post

_admin_resource:
    pattern: /admin/resource/{id}
    defaults: { _controller: opensixt.user_admin.controller.resource:viewAction }
    requirements:
        id: \d+
        _method: get

_admin_resource_save:
    pattern: /admin/resource/{id}/save
    defaults: { _controller: opensixt.user_admin.controller.resource:saveAction }
    requirements:
        id: \d+
        _method: post